import { defineStore } from 'pinia';

const translations = {
  en: {
    appName: 'LifeTracker',
    dashboard: 'Dashboard',
    profile: 'Profile',
    logout: 'Logout',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    language: 'Language',
    welcomeBack: 'Welcome back',
    overview: 'Here is your quick overview for staying focused and productive.',
    settingsNote: 'Switch theme and language anytime to personalize your workspace.',
    signInTitle: 'LifeTracker AI',
    signInDescription: 'Sign in to your productivity dashboard.',
    registerTitle: 'Create your LifeTracker account',
    registerDescription: 'Register to access your productivity dashboard.',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    signIn: 'Sign In',
    register: 'Register',
    haveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    defaultAccountNote: 'Use admin@gmail.com / admin123 to sign in after registering.',
    totalTasks: 'Total tasks',
    completed: 'Completed',
    pending: 'Pending',
    averageFocus: 'Average focus',
    aiAssistantTitle: 'AI Productivity Assistant',
    aiAssistantSubtitle: 'Smart task guidance',
    focusAnalytics: 'Focus analytics',
    motivationHub: 'Motivation hub',
    recentActivityMap: 'Recent activity map',
    logNewActivity: 'Log a new activity',
    recentTasks: 'Recent tasks',
    tasksLogged: 'tasks logged',
    finish: 'Finish',
    completedStatus: 'Completed',
    open: 'Open',
    done: 'Done',
    noTasksYet: 'No tasks yet. Add your first task from the form above.',
    zoneBreakdownTitle: 'Zone breakdown',
    taskReviewTitle: 'Task review',
    taskReviewSubtitle: 'Answer a few questions before completing this task',
    reviewNote: 'Review note',
    trinityChatTitle: 'Trinity Chat',
    trinityChatSubtitle: 'Ask about productivity, planning, or how to improve your task flow.',
    typeQuestionPlaceholder: 'Type a question for the AI assistant',
    askAssistant: 'Ask Assistant',
    thinking: 'Thinking...',
    assistantSays: 'Assistant says',
    answerTaskPrompt: 'Tell me about "{title}" to complete it.',
    questionCount: 'Question {current} of {total}',
    questionAnswerPrompt: 'Type your answer here...',
    you: 'You',
    assistant: 'Assistant',
    answerRequired: 'Please answer the current question before continuing.',
    activityLogged: 'Activity logged successfully.',
    unableLogActivity: 'Unable to log activity.',
    taskTitle: 'Task Title',
    description: 'Description',
    zone: 'Zone',
    selectZone: 'Select zone',
    durationMinutes: 'Duration (minutes)',
    logActivity: 'Log Activity',
    home: 'Home',
    office: 'Office',
    university: 'University',
    itPark: 'IT Park',
    mall: 'Mall',
    profileHeading: 'Personal profile',
    changePhoto: 'Change photo',
    yourDisplayName: 'Your display name',
    updateProfileNote: 'Update your profile name and picture to personalize the dashboard.',
    rank: 'Rank',
    performanceSummary: 'Performance summary',
    tasksCompleted: 'Tasks completed',
    minutesLogged: 'Minutes logged',
    averageFocusLabel: 'Average focus',
    experienceGrowth: 'Experience & Growth',
    masteryResults: 'Mastery results',
    focusStreak: 'Focus streak',
    topZone: 'Top zone',
    studyPower: 'Study power',
    quickYoutubeAccess: 'Quick YouTube Access',
    motivationDescription: 'Open motivational music and study playlists instantly.',
    go: 'Go',
    currentRank: 'Current rank',
    levelToNext: 'Level {level} · {percent}% to next level',
    saveProfile: 'Save profile',
    saving: 'Saving...',
    activityResults: 'Activity results',
    recentInsights: 'Recent insights from your productivity and focus tracking.',
    noStreakYet: 'No streak yet',
    eliteStreak: 'Elite streak',
    strongStreak: 'Strong streak',
    gettingStarted: 'Getting started',
    useDashboardToLog: 'Use the dashboard to log tasks',
    high: 'High',
    medium: 'Medium',
    growing: 'Growing',
    masterTracker: 'Master Tracker',
    productivityPro: 'Productivity Pro',
    focusedRunner: 'Focused Runner',
    noviceBuilder: 'Novice Builder',
  },
  ru: {
    appName: 'LifeTracker',
    dashboard: 'Панель',
    profile: 'Профиль',
    logout: 'Выйти',
    darkMode: 'Темная тема',
    lightMode: 'Светлая тема',
    language: 'Язык',
    welcomeBack: 'С возвращением',
    overview: 'Здесь ваш быстрый обзор для поддержания фокуса и продуктивности.',
    settingsNote: 'Меняйте тему и язык в любое время для персонализации рабочего пространства.',
    signInTitle: 'LifeTracker AI',
    signInDescription: 'Войдите в панель продуктивности.',
    registerTitle: 'Создайте аккаунт LifeTracker',
    registerDescription: 'Зарегистрируйтесь, чтобы получить доступ к вашей панели продуктивности.',
    email: 'Эл. почта',
    password: 'Пароль',
    name: 'Имя',
    signIn: 'Войти',
    register: 'Зарегистрироваться',
    haveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    defaultAccountNote: 'Используйте admin@gmail.com / admin123 для входа после регистрации.',
    totalTasks: 'Всего задач',
    completed: 'Выполнено',
    pending: 'Ожидают',
    averageFocus: 'Средняя концентрация',
    aiAssistantTitle: 'Ассистент продуктивности',
    aiAssistantSubtitle: 'Умное руководство по задачам',
    focusAnalytics: 'Аналитика фокуса',
    motivationHub: 'Центр мотивации',
    recentActivityMap: 'Карта активности',
    logNewActivity: 'Добавить активность',
    recentTasks: 'Последние задачи',
    tasksLogged: 'задач зарегистрировано',
    finish: 'Завершить',
    completedStatus: 'Завершено',
    open: 'Открыть',
    done: 'Готово',
    noTasksYet: 'Пока нет задач. Добавьте первую задачу через форму выше.',
    zoneBreakdownTitle: 'Распределение зон',
    taskReviewTitle: 'Обзор задачи',
    taskReviewSubtitle: 'Ответьте на несколько вопросов перед завершением этой задачи',
    reviewNote: 'Заметка обзора',
    trinityChatTitle: 'Trinity Chat',
    trinityChatSubtitle: 'Спросите о продуктивности, планировании или том, как улучшить рабочий процесс.',
    typeQuestionPlaceholder: 'Напишите вопрос для AI ассистента',
    askAssistant: 'Спросить ассистента',
    thinking: 'Думаю...',
    assistantSays: 'Ассистент говорит',
    answerTaskPrompt: 'Расскажите о задаче "{title}", чтобы завершить ее.',
    questionCount: 'Вопрос {current} из {total}',
    questionAnswerPrompt: 'Введите ответ здесь...',
    you: 'Вы',
    assistant: 'Ассистент',
    answerRequired: 'Пожалуйста, ответьте на текущий вопрос, прежде чем продолжить.',
    activityLogged: 'Активность успешно сохранена.',
    unableLogActivity: 'Не удалось сохранить активность.',
    taskTitle: 'Название задачи',
    description: 'Описание',
    zone: 'Зона',
    selectZone: 'Выберите зону',
    durationMinutes: 'Длительность (минуты)',
    logActivity: 'Сохранить активность',
    home: 'Дом',
    office: 'Офис',
    university: 'Университет',
    itPark: 'IT Парк',
    mall: 'ТЦ',
    profileHeading: 'Персональный профиль',
    changePhoto: 'Поменять фото',
    yourDisplayName: 'Ваше отображаемое имя',
    updateProfileNote: 'Обновите имя и фото профиля, чтобы персонализировать панель.',
    rank: 'Ранг',
    performanceSummary: 'Итоги производительности',
    tasksCompleted: 'Выполнено задач',
    minutesLogged: 'Зарегистрировано минут',
    averageFocusLabel: 'Средняя концентрация',
    experienceGrowth: 'Опыт и рост',
    masteryResults: 'Результаты мастерства',
    focusStreak: 'Серия фокуса',
    topZone: 'Топ зона',
    studyPower: 'Сила обучения',
    quickYoutubeAccess: 'Быстрый доступ к YouTube',
    motivationDescription: 'Откройте мотивационную музыку и плейлисты для учебы за один клик.',
    go: 'Перейти',
    currentRank: 'Текущий ранг',
    levelToNext: 'Уровень {level} · {percent}% до следующего уровня',
    saveProfile: 'Сохранить профиль',
    saving: 'Сохранение...',
    activityResults: 'Результаты активности',
    recentInsights: 'Последние данные о вашей продуктивности и фокусе.',
    noStreakYet: 'Еще нет серии',
    eliteStreak: 'Элитная серия',
    strongStreak: 'Сильная серия',
    gettingStarted: 'Начинаем',
    useDashboardToLog: 'Используйте панель для добавления задач',
    high: 'Высокая',
    medium: 'Средняя',
    growing: 'Растет',
    masterTracker: 'Мастер трекер',
    productivityPro: 'Профи продуктивности',
    focusedRunner: 'Фокусированный бегун',
    noviceBuilder: 'Новичок',
  },
};

const applyTheme = (theme) => {
  document.body.classList.toggle('theme-dark', theme === 'dark');
};

export const useUiStore = defineStore('ui', {
  state: () => ({
    theme: localStorage.getItem('lifetracker_theme') || 'light',
    locale: localStorage.getItem('lifetracker_locale') || 'en',
  }),
  getters: {
    translate: (state) => {
      return (key, params = {}) => {
        const raw = translations[state.locale]?.[key] || translations.en[key] || key;
        return raw.replace(/\{(\w+)\}/g, (_, name) => params[name] ?? `{${name}}`);
      };
    },
    isDarkTheme: (state) => state.theme === 'dark',
  },
  actions: {
    initialize() {
      applyTheme(this.theme);
    },
    setTheme(theme) {
      this.theme = theme;
      localStorage.setItem('lifetracker_theme', theme);
      applyTheme(theme);
    },
    toggleTheme() {
      const nextTheme = this.theme === 'dark' ? 'light' : 'dark';
      this.setTheme(nextTheme);
    },
    setLocale(locale) {
      this.locale = locale;
      localStorage.setItem('lifetracker_locale', locale);
    },
  },
});
